package com.autumnframework.cms.dao;

import com.autumnframework.cms.model.po.Plugin;

public interface PluginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_plugin
     *
     * @mbg.generated Tue Oct 31 08:54:20 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_plugin
     *
     * @mbg.generated Tue Oct 31 08:54:20 CST 2017
     */
    int insert(Plugin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_plugin
     *
     * @mbg.generated Tue Oct 31 08:54:20 CST 2017
     */
    int insertSelective(Plugin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_plugin
     *
     * @mbg.generated Tue Oct 31 08:54:20 CST 2017
     */
    Plugin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_plugin
     *
     * @mbg.generated Tue Oct 31 08:54:20 CST 2017
     */
    int updateByPrimaryKeySelective(Plugin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_plugin
     *
     * @mbg.generated Tue Oct 31 08:54:20 CST 2017
     */
    int updateByPrimaryKey(Plugin record);
}