/**
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2017 © yangxiaobing, 873559947@qq.com
 *
 * This file is part of contentManagerSystem.
 * contentManagerSystem is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * contentManagerSystem is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with contentManagerSystem.  If not, see <http://www.gnu.org/licenses/>.
 *
 * 这个文件是contentManagerSystem的一部分。
 * 您可以单独使用或分发这个文件，但请不要移除这个头部声明信息.
 * contentManagerSystem是一个自由软件，您可以自由分发、修改其中的源代码或者重新发布它，
 * 新的任何修改后的重新发布版必须同样在遵守GPL3或更后续的版本协议下发布.
 * 关于GPL协议的细则请参考COPYING文件，
 * 您可以在contentManagerSystem的相关目录中获得GPL协议的副本，
 * 如果没有找到，请连接到 http://www.gnu.org/licenses/ 查看。
 *
 * - Author: yangxiaobing
 * - Contact: 873559947@qq.com
 * - License: GNU Lesser General Public License (GPL)
 * - source code availability: http://git.oschina.net/yangxiaobing_175/contentManagerSystem
 */
package com.yxb.cms.domain.vo;


import com.yxb.cms.domain.dto.PageDto;

import java.io.Serializable;
import java.util.Date;

/**
 * 菜单资源实体
 * @author yangxiaobing
 * @date  2017/7/21
 *
 */
public class Resource extends PageDto implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_resource.res_id
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    private Integer resId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_resource.res_parentId
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    private Integer resParentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_resource.res_name
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    private String resName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_resource.res_model_type
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    private String resModelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_resource.res_link_address
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    private String resLinkAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_resource.res_image
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    private String resImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_resource.res_level
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    private Integer resLevel;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_resource.res_type
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    private Integer resType;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_resource.res_status
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    private Integer resStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_resource.res_display_order
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    private Integer resDisplayOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_resource.res_remark
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    private String resRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_resource.creator
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_resource.create_time
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_resource.modifier
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_resource.modify_time
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_resource.res_id
     *
     * @return the value of cc_resource.res_id
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    
    //新增字段,方便页面显示
    /**图标**/
    private String iconCls;
    /**父级资源名称**/
    private String parentname;
    
    private String beginTime;
    private String endTime;

    /**
     * 查询项
     */
    private String searchTerm;
    /**
     * 查询内容
     */
    private String searchContent;
    
    
    
    public Integer getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_resource.res_id
     *
     * @param resId the value for cc_resource.res_id
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public void setResId(Integer resId) {
        this.resId = resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_resource.res_parentId
     *
     * @return the value of cc_resource.res_parentId
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public Integer getResParentid() {
        return resParentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_resource.res_parentId
     *
     * @param resParentid the value for cc_resource.res_parentId
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public void setResParentid(Integer resParentid) {
        this.resParentid = resParentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_resource.res_name
     *
     * @return the value of cc_resource.res_name
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public String getResName() {
        return resName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_resource.res_name
     *
     * @param resName the value for cc_resource.res_name
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public void setResName(String resName) {
        this.resName = resName == null ? null : resName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_resource.res_model_type
     *
     * @return the value of cc_resource.res_model_type
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public String getResModelCode() {
        return resModelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_resource.res_model_type
     *
     * @param resModelType the value for cc_resource.res_model_type
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public void setResModelCode(String resModelCode) {
        this.resModelCode = resModelCode == null ? null : resModelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_resource.res_link_address
     *
     * @return the value of cc_resource.res_link_address
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public String getResLinkAddress() {
        return resLinkAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_resource.res_link_address
     *
     * @param resLinkAddress the value for cc_resource.res_link_address
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public void setResLinkAddress(String resLinkAddress) {
        this.resLinkAddress = resLinkAddress == null ? null : resLinkAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_resource.res_image
     *
     * @return the value of cc_resource.res_image
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public String getResImage() {
        return resImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_resource.res_image
     *
     * @param resImage the value for cc_resource.res_image
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public void setResImage(String resImage) {
        this.resImage = resImage == null ? null : resImage.trim();
    }

    public Integer getResLevel() {
        return resLevel;
    }

    public void setResLevel(Integer resLevel) {
        this.resLevel = resLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_resource.res_type
     *
     * @return the value of cc_resource.res_type
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public Integer getResType() {
        return resType;
    }

    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_resource.res_type
     *
     * @param resType the value for cc_resource.res_type
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public void setResType(Integer resType) {
        this.resType = resType;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_resource.res_status
     *
     * @return the value of cc_resource.res_type
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public Integer getResStatus() {
        return resStatus;
    }

    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_resource.res_status
     *
     * @param resType the value for cc_resource.resStatus
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public void setResStatus(Integer resStatus) {
        this.resStatus = resStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_resource.res_display_order
     *
     * @return the value of cc_resource.res_display_order
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public Integer getResDisplayOrder() {
        return resDisplayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_resource.res_display_order
     *
     * @param resDisplayOrder the value for cc_resource.res_display_order
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public void setResDisplayOrder(Integer resDisplayOrder) {
        this.resDisplayOrder = resDisplayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_resource.res_remark
     *
     * @return the value of cc_resource.res_remark
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public String getResRemark() {
        return resRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_resource.res_remark
     *
     * @param resRemark the value for cc_resource.res_remark
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public void setResRemark(String resRemark) {
        this.resRemark = resRemark == null ? null : resRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_resource.creator
     *
     * @return the value of cc_resource.creator
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_resource.creator
     *
     * @param creator the value for cc_resource.creator
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_resource.create_time
     *
     * @return the value of cc_resource.create_time
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_resource.create_time
     *
     * @param createTime the value for cc_resource.create_time
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_resource.modifier
     *
     * @return the value of cc_resource.modifier
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_resource.modifier
     *
     * @param modifier the value for cc_resource.modifier
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_resource.modify_time
     *
     * @return the value of cc_resource.modify_time
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_resource.modify_time
     *
     * @param modifyTime the value for cc_resource.modify_time
     *
     * @mbggenerated Mon Aug 15 17:19:21 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }    
	public String getBeginTime() {
		return beginTime;
	}

	public void setBeginTime(String beginTime) {
		this.beginTime = beginTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getIconCls() {
		return iconCls;
	}

	public void setIconCls(String iconCls) {
		this.iconCls = iconCls;
	}

	public String getParentname() {
		return parentname;
	}

	public void setParentname(String parentname) {
		this.parentname = parentname;
	}

    public String getSearchTerm() {
        return searchTerm;
    }

    public void setSearchTerm(String searchTerm) {
        this.searchTerm = searchTerm;
    }

    public String getSearchContent() {
        return searchContent;
    }

    public void setSearchContent(String searchContent) {
        this.searchContent = searchContent;
    }
}