package com.autumnframework.login.dao1;

import com.autumnframework.login.model.po.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_user
     *
     * @mbg.generated Wed Sep 06 09:53:56 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_user
     *
     * @mbg.generated Wed Sep 06 09:53:56 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_user
     *
     * @mbg.generated Wed Sep 06 09:53:56 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_user
     *
     * @mbg.generated Wed Sep 06 09:53:56 CST 2017
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_user
     *
     * @mbg.generated Wed Sep 06 09:53:56 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_user
     *
     * @mbg.generated Wed Sep 06 09:53:56 CST 2017
     */
    int updateByPrimaryKey(User record);
}