package com.autumnframework.login.model.po;

import java.util.Date;

public class Resource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_resource.id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_resource.parent_id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    private Integer parent_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_resource.namee
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    private String namee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_resource.namec
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    private String namec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_resource.status
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_resource.link_address
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    private String link_address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_resource.icon
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_resource.level
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_resource.type
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_resource.remark
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_resource.creator
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_resource.creator_id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    private Integer creator_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_resource.create_time
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_resource.modifier
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_resource.modifier_id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    private Integer modifier_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_resource.modifier_time
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    private Date modifier_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_resource.id
     *
     * @return the value of af_resource.id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_resource.id
     *
     * @param id the value for af_resource.id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_resource.parent_id
     *
     * @return the value of af_resource.parent_id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public Integer getParent_id() {
        return parent_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_resource.parent_id
     *
     * @param parent_id the value for af_resource.parent_id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public void setParent_id(Integer parent_id) {
        this.parent_id = parent_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_resource.namee
     *
     * @return the value of af_resource.namee
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public String getNamee() {
        return namee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_resource.namee
     *
     * @param namee the value for af_resource.namee
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public void setNamee(String namee) {
        this.namee = namee == null ? null : namee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_resource.namec
     *
     * @return the value of af_resource.namec
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public String getNamec() {
        return namec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_resource.namec
     *
     * @param namec the value for af_resource.namec
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public void setNamec(String namec) {
        this.namec = namec == null ? null : namec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_resource.status
     *
     * @return the value of af_resource.status
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_resource.status
     *
     * @param status the value for af_resource.status
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_resource.link_address
     *
     * @return the value of af_resource.link_address
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public String getLink_address() {
        return link_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_resource.link_address
     *
     * @param link_address the value for af_resource.link_address
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public void setLink_address(String link_address) {
        this.link_address = link_address == null ? null : link_address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_resource.icon
     *
     * @return the value of af_resource.icon
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_resource.icon
     *
     * @param icon the value for af_resource.icon
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_resource.level
     *
     * @return the value of af_resource.level
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_resource.level
     *
     * @param level the value for af_resource.level
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_resource.type
     *
     * @return the value of af_resource.type
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_resource.type
     *
     * @param type the value for af_resource.type
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_resource.remark
     *
     * @return the value of af_resource.remark
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_resource.remark
     *
     * @param remark the value for af_resource.remark
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_resource.creator
     *
     * @return the value of af_resource.creator
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_resource.creator
     *
     * @param creator the value for af_resource.creator
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_resource.creator_id
     *
     * @return the value of af_resource.creator_id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_resource.creator_id
     *
     * @param creator_id the value for af_resource.creator_id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_resource.create_time
     *
     * @return the value of af_resource.create_time
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_resource.create_time
     *
     * @param create_time the value for af_resource.create_time
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_resource.modifier
     *
     * @return the value of af_resource.modifier
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_resource.modifier
     *
     * @param modifier the value for af_resource.modifier
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_resource.modifier_id
     *
     * @return the value of af_resource.modifier_id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public Integer getModifier_id() {
        return modifier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_resource.modifier_id
     *
     * @param modifier_id the value for af_resource.modifier_id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public void setModifier_id(Integer modifier_id) {
        this.modifier_id = modifier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_resource.modifier_time
     *
     * @return the value of af_resource.modifier_time
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public Date getModifier_time() {
        return modifier_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_resource.modifier_time
     *
     * @param modifier_time the value for af_resource.modifier_time
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public void setModifier_time(Date modifier_time) {
        this.modifier_time = modifier_time;
    }
}