package com.autumnframework.cms.dao.bomapper;

import com.autumnframework.cms.model.po.RoleResource;

public interface RoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_role_resource
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_role_resource
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    int insert(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_role_resource
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    int insertSelective(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_role_resource
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    RoleResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_role_resource
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    int updateByPrimaryKeySelective(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_role_resource
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    int updateByPrimaryKey(RoleResource record);
}