package com.autumnframework.cms.model.po;

import java.util.Date;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_role.id
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_role.role_name
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    private String role_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_role.status
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_role.creator
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_role.creator_id
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    private Integer creator_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_role.create_time
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_role.modifier
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_role.mofifier_id
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    private Integer mofifier_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_role.modifier_time
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    private Date modifier_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_role.id
     *
     * @return the value of af_role.id
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_role.id
     *
     * @param id the value for af_role.id
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_role.role_name
     *
     * @return the value of af_role.role_name
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    public String getRole_name() {
        return role_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_role.role_name
     *
     * @param role_name the value for af_role.role_name
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    public void setRole_name(String role_name) {
        this.role_name = role_name == null ? null : role_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_role.status
     *
     * @return the value of af_role.status
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_role.status
     *
     * @param status the value for af_role.status
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_role.creator
     *
     * @return the value of af_role.creator
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_role.creator
     *
     * @param creator the value for af_role.creator
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_role.creator_id
     *
     * @return the value of af_role.creator_id
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_role.creator_id
     *
     * @param creator_id the value for af_role.creator_id
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_role.create_time
     *
     * @return the value of af_role.create_time
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_role.create_time
     *
     * @param create_time the value for af_role.create_time
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_role.modifier
     *
     * @return the value of af_role.modifier
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_role.modifier
     *
     * @param modifier the value for af_role.modifier
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_role.mofifier_id
     *
     * @return the value of af_role.mofifier_id
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    public Integer getMofifier_id() {
        return mofifier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_role.mofifier_id
     *
     * @param mofifier_id the value for af_role.mofifier_id
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    public void setMofifier_id(Integer mofifier_id) {
        this.mofifier_id = mofifier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_role.modifier_time
     *
     * @return the value of af_role.modifier_time
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    public Date getModifier_time() {
        return modifier_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_role.modifier_time
     *
     * @param modifier_time the value for af_role.modifier_time
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    public void setModifier_time(Date modifier_time) {
        this.modifier_time = modifier_time;
    }
}