package com.autumnframework.cms.model.po;

import java.util.Date;

public class RoleResource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_role_resource.id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_role_resource.role_id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    private Integer role_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_role_resource.resource_id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    private Integer resource_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_role_resource.creator
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_role_resource.creator_id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    private Integer creator_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_role_resource.create_time
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_role_resource.modifier
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_role_resource.modifier_id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    private Integer modifier_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_role_resource.modifier_time
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    private Date modifier_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_role_resource.id
     *
     * @return the value of af_role_resource.id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_role_resource.id
     *
     * @param id the value for af_role_resource.id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_role_resource.role_id
     *
     * @return the value of af_role_resource.role_id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public Integer getRole_id() {
        return role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_role_resource.role_id
     *
     * @param role_id the value for af_role_resource.role_id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public void setRole_id(Integer role_id) {
        this.role_id = role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_role_resource.resource_id
     *
     * @return the value of af_role_resource.resource_id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public Integer getResource_id() {
        return resource_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_role_resource.resource_id
     *
     * @param resource_id the value for af_role_resource.resource_id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public void setResource_id(Integer resource_id) {
        this.resource_id = resource_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_role_resource.creator
     *
     * @return the value of af_role_resource.creator
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_role_resource.creator
     *
     * @param creator the value for af_role_resource.creator
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_role_resource.creator_id
     *
     * @return the value of af_role_resource.creator_id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_role_resource.creator_id
     *
     * @param creator_id the value for af_role_resource.creator_id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_role_resource.create_time
     *
     * @return the value of af_role_resource.create_time
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_role_resource.create_time
     *
     * @param create_time the value for af_role_resource.create_time
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_role_resource.modifier
     *
     * @return the value of af_role_resource.modifier
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_role_resource.modifier
     *
     * @param modifier the value for af_role_resource.modifier
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_role_resource.modifier_id
     *
     * @return the value of af_role_resource.modifier_id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public Integer getModifier_id() {
        return modifier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_role_resource.modifier_id
     *
     * @param modifier_id the value for af_role_resource.modifier_id
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public void setModifier_id(Integer modifier_id) {
        this.modifier_id = modifier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_role_resource.modifier_time
     *
     * @return the value of af_role_resource.modifier_time
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public Date getModifier_time() {
        return modifier_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_role_resource.modifier_time
     *
     * @param modifier_time the value for af_role_resource.modifier_time
     *
     * @mbg.generated Sun Oct 29 11:22:33 CST 2017
     */
    public void setModifier_time(Date modifier_time) {
        this.modifier_time = modifier_time;
    }
}