package com.autumnframework.cms.model.po;

import java.util.Date;

public class LoginInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_logininfo.id
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_logininfo.ip
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_logininfo.area
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_logininfo.area_id
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    private String area_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_logininfo.city
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_logininfo.city_id
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    private String city_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_logininfo.country
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_logininfo.country_id
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    private String country_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_logininfo.county
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    private String county;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_logininfo.county_id
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    private String county_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_logininfo.isp
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    private String isp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_logininfo.isp_id
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    private String isp_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_logininfo.region
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_logininfo.region_id
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    private String region_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_logininfo.visit_time
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    private Date visit_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_logininfo.user_login_name
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    private String user_login_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_logininfo.id
     *
     * @return the value of af_logininfo.id
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_logininfo.id
     *
     * @param id the value for af_logininfo.id
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_logininfo.ip
     *
     * @return the value of af_logininfo.ip
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_logininfo.ip
     *
     * @param ip the value for af_logininfo.ip
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_logininfo.area
     *
     * @return the value of af_logininfo.area
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_logininfo.area
     *
     * @param area the value for af_logininfo.area
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_logininfo.area_id
     *
     * @return the value of af_logininfo.area_id
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public String getArea_id() {
        return area_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_logininfo.area_id
     *
     * @param area_id the value for af_logininfo.area_id
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public void setArea_id(String area_id) {
        this.area_id = area_id == null ? null : area_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_logininfo.city
     *
     * @return the value of af_logininfo.city
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_logininfo.city
     *
     * @param city the value for af_logininfo.city
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_logininfo.city_id
     *
     * @return the value of af_logininfo.city_id
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public String getCity_id() {
        return city_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_logininfo.city_id
     *
     * @param city_id the value for af_logininfo.city_id
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public void setCity_id(String city_id) {
        this.city_id = city_id == null ? null : city_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_logininfo.country
     *
     * @return the value of af_logininfo.country
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_logininfo.country
     *
     * @param country the value for af_logininfo.country
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_logininfo.country_id
     *
     * @return the value of af_logininfo.country_id
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public String getCountry_id() {
        return country_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_logininfo.country_id
     *
     * @param country_id the value for af_logininfo.country_id
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public void setCountry_id(String country_id) {
        this.country_id = country_id == null ? null : country_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_logininfo.county
     *
     * @return the value of af_logininfo.county
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_logininfo.county
     *
     * @param county the value for af_logininfo.county
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_logininfo.county_id
     *
     * @return the value of af_logininfo.county_id
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public String getCounty_id() {
        return county_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_logininfo.county_id
     *
     * @param county_id the value for af_logininfo.county_id
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public void setCounty_id(String county_id) {
        this.county_id = county_id == null ? null : county_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_logininfo.isp
     *
     * @return the value of af_logininfo.isp
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public String getIsp() {
        return isp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_logininfo.isp
     *
     * @param isp the value for af_logininfo.isp
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public void setIsp(String isp) {
        this.isp = isp == null ? null : isp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_logininfo.isp_id
     *
     * @return the value of af_logininfo.isp_id
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public String getIsp_id() {
        return isp_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_logininfo.isp_id
     *
     * @param isp_id the value for af_logininfo.isp_id
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public void setIsp_id(String isp_id) {
        this.isp_id = isp_id == null ? null : isp_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_logininfo.region
     *
     * @return the value of af_logininfo.region
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_logininfo.region
     *
     * @param region the value for af_logininfo.region
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_logininfo.region_id
     *
     * @return the value of af_logininfo.region_id
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public String getRegion_id() {
        return region_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_logininfo.region_id
     *
     * @param region_id the value for af_logininfo.region_id
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public void setRegion_id(String region_id) {
        this.region_id = region_id == null ? null : region_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_logininfo.visit_time
     *
     * @return the value of af_logininfo.visit_time
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public Date getVisit_time() {
        return visit_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_logininfo.visit_time
     *
     * @param visit_time the value for af_logininfo.visit_time
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public void setVisit_time(Date visit_time) {
        this.visit_time = visit_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_logininfo.user_login_name
     *
     * @return the value of af_logininfo.user_login_name
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public String getUser_login_name() {
        return user_login_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_logininfo.user_login_name
     *
     * @param user_login_name the value for af_logininfo.user_login_name
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    public void setUser_login_name(String user_login_name) {
        this.user_login_name = user_login_name == null ? null : user_login_name.trim();
    }

    @Override
    public String toString() {
        return "LoginInfo{" +
                "id=" + id +
                ", ip='" + ip + '\'' +
                ", area='" + area + '\'' +
                ", area_id='" + area_id + '\'' +
                ", city='" + city + '\'' +
                ", city_id='" + city_id + '\'' +
                ", country='" + country + '\'' +
                ", country_id='" + country_id + '\'' +
                ", county='" + county + '\'' +
                ", county_id='" + county_id + '\'' +
                ", isp='" + isp + '\'' +
                ", isp_id='" + isp_id + '\'' +
                ", region='" + region + '\'' +
                ", region_id='" + region_id + '\'' +
                ", visit_time=" + visit_time +
                ", user_login_name='" + user_login_name + '\'' +
                '}';
    }
}