package com.autumnframework.cms.model.po;

public class Plugin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_plugin.id
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_plugin.sys
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    private String sys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_plugin.name
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_plugin.namee
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    private String namee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_plugin.namec
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    private String namec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_plugin.titlee
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    private String titlee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_plugin.titlec
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    private String titlec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_plugin.autorun
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    private Integer autorun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_plugin.plugin
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    private String plugin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_plugin.dir
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    private String dir;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_plugin.jsurl
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    private String jsurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_plugin.htmleurl
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    private String htmleurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_plugin.htmlcurl
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    private String htmlcurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_plugin.icon
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_plugin.status
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_plugin.id
     *
     * @return the value of af_plugin.id
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_plugin.id
     *
     * @param id the value for af_plugin.id
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_plugin.sys
     *
     * @return the value of af_plugin.sys
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public String getSys() {
        return sys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_plugin.sys
     *
     * @param sys the value for af_plugin.sys
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public void setSys(String sys) {
        this.sys = sys == null ? null : sys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_plugin.name
     *
     * @return the value of af_plugin.name
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_plugin.name
     *
     * @param name the value for af_plugin.name
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_plugin.namee
     *
     * @return the value of af_plugin.namee
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public String getNamee() {
        return namee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_plugin.namee
     *
     * @param namee the value for af_plugin.namee
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public void setNamee(String namee) {
        this.namee = namee == null ? null : namee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_plugin.namec
     *
     * @return the value of af_plugin.namec
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public String getNamec() {
        return namec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_plugin.namec
     *
     * @param namec the value for af_plugin.namec
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public void setNamec(String namec) {
        this.namec = namec == null ? null : namec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_plugin.titlee
     *
     * @return the value of af_plugin.titlee
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public String getTitlee() {
        return titlee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_plugin.titlee
     *
     * @param titlee the value for af_plugin.titlee
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public void setTitlee(String titlee) {
        this.titlee = titlee == null ? null : titlee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_plugin.titlec
     *
     * @return the value of af_plugin.titlec
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public String getTitlec() {
        return titlec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_plugin.titlec
     *
     * @param titlec the value for af_plugin.titlec
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public void setTitlec(String titlec) {
        this.titlec = titlec == null ? null : titlec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_plugin.autorun
     *
     * @return the value of af_plugin.autorun
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public Integer getAutorun() {
        return autorun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_plugin.autorun
     *
     * @param autorun the value for af_plugin.autorun
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public void setAutorun(Integer autorun) {
        this.autorun = autorun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_plugin.plugin
     *
     * @return the value of af_plugin.plugin
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public String getPlugin() {
        return plugin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_plugin.plugin
     *
     * @param plugin the value for af_plugin.plugin
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public void setPlugin(String plugin) {
        this.plugin = plugin == null ? null : plugin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_plugin.dir
     *
     * @return the value of af_plugin.dir
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public String getDir() {
        return dir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_plugin.dir
     *
     * @param dir the value for af_plugin.dir
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public void setDir(String dir) {
        this.dir = dir == null ? null : dir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_plugin.jsurl
     *
     * @return the value of af_plugin.jsurl
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public String getJsurl() {
        return jsurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_plugin.jsurl
     *
     * @param jsurl the value for af_plugin.jsurl
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public void setJsurl(String jsurl) {
        this.jsurl = jsurl == null ? null : jsurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_plugin.htmleurl
     *
     * @return the value of af_plugin.htmleurl
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public String getHtmleurl() {
        return htmleurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_plugin.htmleurl
     *
     * @param htmleurl the value for af_plugin.htmleurl
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public void setHtmleurl(String htmleurl) {
        this.htmleurl = htmleurl == null ? null : htmleurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_plugin.htmlcurl
     *
     * @return the value of af_plugin.htmlcurl
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public String getHtmlcurl() {
        return htmlcurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_plugin.htmlcurl
     *
     * @param htmlcurl the value for af_plugin.htmlcurl
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public void setHtmlcurl(String htmlcurl) {
        this.htmlcurl = htmlcurl == null ? null : htmlcurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_plugin.icon
     *
     * @return the value of af_plugin.icon
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_plugin.icon
     *
     * @param icon the value for af_plugin.icon
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_plugin.status
     *
     * @return the value of af_plugin.status
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_plugin.status
     *
     * @param status the value for af_plugin.status
     *
     * @mbg.generated Mon Oct 30 21:05:07 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return "Plugin{" +
                "id=" + id +
                ", sys='" + sys + '\'' +
                ", name='" + name + '\'' +
                ", namee='" + namee + '\'' +
                ", namec='" + namec + '\'' +
                ", titlee='" + titlee + '\'' +
                ", titlec='" + titlec + '\'' +
                ", autorun=" + autorun +
                ", plugin='" + plugin + '\'' +
                ", dir='" + dir + '\'' +
                ", jsurl='" + jsurl + '\'' +
                ", htmleurl='" + htmleurl + '\'' +
                ", htmlcurl='" + htmlcurl + '\'' +
                ", icon='" + icon + '\'' +
                ", status=" + status +
                '}';
    }
}