package com.autumnframework.cms.dao.bomapper;

import com.autumnframework.cms.model.po.LoginInfo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface LoginInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_logininfo
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_logininfo
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    int insert(LoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_logininfo
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    int insertSelective(LoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_logininfo
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    LoginInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_logininfo
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    int updateByPrimaryKeySelective(LoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_logininfo
     *
     * @mbg.generated Tue Oct 31 19:49:31 CST 2017
     */
    int updateByPrimaryKey(LoginInfo record);
    /**
     * 获取所有登录信息
     * @return
     */
    List<LoginInfo> selectAllLoginInfo(@Param("start") int start, @Param("end") int end);

    /**
     * 获取某用户登录信息
     * @param username
     * @return
     */
    List<LoginInfo> selectLoginInfoByUserName(@Param("username") String username, @Param("start") int start, @Param("end") int end);

}