package com.autumnframework.cms.dao.bomapper;

import com.autumnframework.cms.model.po.RolePlugin;
import org.springframework.stereotype.Repository;

@Repository
public interface RolePluginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_role_plugin
     *
     * @mbg.generated Mon Oct 30 21:05:52 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_role_plugin
     *
     * @mbg.generated Mon Oct 30 21:05:52 CST 2017
     */
    int insert(RolePlugin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_role_plugin
     *
     * @mbg.generated Mon Oct 30 21:05:52 CST 2017
     */
    int insertSelective(RolePlugin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_role_plugin
     *
     * @mbg.generated Mon Oct 30 21:05:52 CST 2017
     */
    RolePlugin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_role_plugin
     *
     * @mbg.generated Mon Oct 30 21:05:52 CST 2017
     */
    int updateByPrimaryKeySelective(RolePlugin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_role_plugin
     *
     * @mbg.generated Mon Oct 30 21:05:52 CST 2017
     */
    int updateByPrimaryKey(RolePlugin record);
}