/*地图主视图模块*/
                        delete from plugin where name = 'MonitorMan';         insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara)values ('11','MonitorMan','MonitorMan','人员监控','MonitorMan','人员监控',1,1,null,null,3,0,'tabsMoniMan',0,'MonitorMan','cx.plug.MonitorMan','plugin/xunjian/mainview/MonitorMan/','MonitorMan.js','MonitorMan.html','MonitorManC.html',null,0,420,160,null,null);
                        delete from plugin where name = 'MonitorCar';         insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara)values ('11','MonitorCar','MonitorCar','车辆监控','MonitorCar','车辆监控',1,1,null,null,3,0,'tabsMoniCar',0,'MonitorCar','cx.plug.MonitorCar','plugin/xunjian/mainview/MonitorCar/','MonitorCar.js','MonitorCar.html','MonitorCarC.html',null,0,420,160,null,null);
                        delete from plugin where name = 'MonitorHid';         insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara)values ('11','MonitorHid','MonitorHid','隐患监控','MonitorHid','隐患监控',1,1,null,null,3,0,'tabsMoniHid',0,'MonitorHid','cx.plug.MonitorHid','plugin/xunjian/mainview/MonitorHid/','MonitorHid.js','MonitorHid.html','MonitorHidC.html',null,0,420,160,null,null);
                        delete from plugin where name = 'MonitorMal';         insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara)values ('11','MonitorMal','MonitorMal','故障监控','MonitorMal','故障监控',1,1,null,null,3,0,'tabsMoniMal',0,'MonitorMan','cx.plug.MonitorMal','plugin/xunjian/mainview/MonitorMal/','MonitorMal.js','MonitorMal.html','MonitorMalC.html',null,0,420,160,null,null);
/*隐患管理模块*/

/*待派发任务*/          delete from plugin where name='WaTask';                     insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara) values ('11','WaTask',         'WaTask',           '待派发任务',     'WaTask',          '待派发任务',      0,1,null,null,1,0,null,0,'WaTask','cx.plug.WaTask','plugin/xunjian/manpnt/WaTask/','WaTask.js','WaTask.html','WaTaskC.html','WaTask',0,600,400,null,'{"_major":1,"_minor":9}');
/*审核意见*/            delete from plugin where name ='CheckAd';                   insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara)values ('11',  'CheckAd',       'CheckAd',           '审核意见',    'CheckAd',           '审核意见',        0,1,null,null,1,1,null,0,'CheckAd', 'cx.plug.CheckAd','plugin/xunjian/manpnt/CheckAd/','CheckAd.js', 'CheckAd.html', 'CheckAdC.html', null, 0,310,350, null,  null);
/*任务派发*/            delete from plugin where name='HtOut';                       insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara) values ('11','HtOut',           'HtOut',           '任务派发',      'HtOut',            '任务派发',         0,1,null,null,1,0,null,0,'HtOut','cx.plug.HtOut','plugin/xunjian/manpnt/HtOut/','HtOut.js','HtOut.html','HtOutC.html','HtOut',0,500,400,null,'{"_major":99,"_minor":13}');
/*隐患审核*/            delete from plugin where name='HtAd';                        insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara) values ('11','HtAd',            'HtAd',             '隐患审核',     'HtAd',             '隐患审核',          0,1,null,null,1,0,null,0,'HtAd','cx.plug.HtAd','plugin/xunjian/manpnt/HtAd/','HtAd.js','HtAd.html','HtAdC.html','HtAd',0,600,400,null,'{"_major":1,"_minor":9}');
/*我的隐患*/            delete from plugin where name='MyHt';                        insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara) values ('11','MyHt',            'MyHt',             '我的隐患',     'MyHt',             '我的隐患',          0,1,null,null,1,0,null,0,'MyHt','cx.plug.MyHt','plugin/xunjian/manpnt/MyHt/','MyHt.js','MyHt.html','MyHtC.html','MyHt',0,600,400,null,'{"_major":1,"_minor":9}');
/*任务审核意见*/        delete from plugin where name = 'TaskCheckAdvice';         insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara)values ('11','TaskCheckAdvice','TaskCheckAdvice', '任务审核意见','TaskCheckAdvice', '任务审核意见',     0,1,null,null,1,1,null,0,'TaskCheckAdvice',    'cx.plug.TaskCheckAdvice','plugin/xunjian/manpnt/TaskCheckAdvice/','TaskCheckAdvice.js','TaskCheckAdvice.html','TaskCheckAdviceC.html',          null,      0,310,350, null,   null);


/*任务审核*/            delete from plugin where name = 'TaskCheck';                insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara) values ('11', 'TaskCheck',   'TaskCheck',   '任务审核',     'TaskCheck',    '任务审核',    0,1,null,null,   1,0,null,   0, 'TaskCheck',    'cx.plug.TaskCheck', 'plugin/xunjian/manpnt/TaskCheck/', 'TaskCheck.js', 'TaskCheck.html',    'TaskCheckC.html',   'drawcirc',0,500,350,null,   '{"_major":7,"_minor":7}');
/*隐患查询*/            delete from plugin where name = 'HidanQue';                 insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara) values ('11', 'HidanQue',    'HidanQue',     '隐患查询',     'HidanQue',     '隐患查询',    0,1,null,null,   1,0,null,  0, 'HidanQue',     'cx.plug.HidanQue',  'plugin/xunjian/manpnt/HidanQue/',  'HidanQue.js',  'HidanQue.html',      'HidanQueC.html',     'drawcirc',0,500,350,null,   '{"_major":1,"_minor":9}');
/*隐患统计*/            delete from plugin where name = 'HidanSta';                 insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara) values ('11', 'HidanSta',    'HidanSta',     '隐患统计',     'HidanSta',     '隐患统计',    0,1,null,null,   1,0,null,  0, 'HidanSta',     'cx.plug.HidanSta',  'plugin/xunjian/manpnt/HidanSta/',  'HidanSta.js',  'HidanSta.html',      'HidanStaC.html',     'drawcirc',0,500,350,null,   '{"_major":1,"_minor":9}');
/*柱状图*/              delete from plugin where name = 'histogram';                insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara) values ('11', 'histogram', 'histogram',      '柱状图',       'histogram',    '柱状图',      0, 1,null,null, 1, 0,null,  0, 'histogram',    'cx.plug.histogram',   'plugin/xunjian/charts/histogram/', 'histogram.js' ,NULL, 'histogramC.html', '.zhu', 0, 600, 350,NULL,NULL);
/*线状图*/              delete from plugin where name = 'curvegraph';               insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara) values ('11', 'curvegraph', 'curvegraph',    '线状图',      'curvegraph',    '线状图',      0, 1,null,null, 1, 0,null, 0,'curvegraph' ,   'cx.plug.curvegraph', 'plugin/xunjian/charts/curvegraph/', 'curvegraph.js',NULL, 'curvegraphC.html', '.zhu', 0, 600, 350,NULL,NULL);
/*饼状图*/              delete from plugin where name = 'pie';                       insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara) values ('11', 'pie',         'pie',            '饼状图',       'pie',            '饼状图',      0, 1,null,null, 1, 0,null, 0, 'pie',           'cx.plug.pie',          'plugin/xunjian/charts/pie/', 'pie.js',        NULL,'pieC.html',          '.zhu', 0, 600, 350,NULL,NULL);


/*故障管理模块*/
/*故障审核*/            delete from plugin where name='fHtAd';                insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara) values ('11','fHtAd',            'fHtAd',             '故障审核',     'fHtAd',             '故障审核',          0,1,null,null,1,0,null,0,'fHtAd','cx.plug.fHtAd','plugin/xunjian/manfault/fHtAd/','fHtAd.js','fHtAd.html','fHtAdC.html','fHtAd',0,600,400,null,'{"_major":1,"_minor":10}');
/*我的故障*/            delete from plugin where name='fMyHt';                insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara) values ('11','fMyHt',            'fMyHt',             '我的故障',     'fMyHt',             '我的故障',          0,1,null,null,1,0,null,0,'fMyHt','cx.plug.fMyHt','plugin/xunjian/manfault/fMyHt/','fMyHt.js','fMyHt.html','fMyHtC.html','fMyHt',0,600,400,null,'{"_major":1,"_minor":10}');
/*待派发任务*/          delete from plugin where name='fWaTask';              insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara) values ('11','fWaTask',         'fWaTask',           '待派发任务',     'fWaTask',          '待派发任务',      0,1,null,null,1,0,null,0,'fWaTask','cx.plug.fWaTask','plugin/xunjian/manfault/fWaTask/','fWaTask.js','fWaTask.html','fWaTaskC.html','fWaTask',0,600,400,null,'{"_major":1,"_minor":10}');
/*审核意见*/            delete from plugin where name ='fCheckAd';            insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara)values ('11',  'fCheckAd',       'fCheckAd',           '审核意见',    'fCheckAd',           '审核意见',        0,1,null,null,1,1,null,0,'fCheckAd', 'cx.plug.fCheckAd','plugin/xunjian/manfault/fCheckAd/','fCheckAd.js', 'fCheckAd.html', 'fCheckAdC.html', null, 0,310,350, null,  null);
/*任务派发*/            delete from plugin where name='fHtOut';               insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara) values ('11','fHtOut',           'fHtOut',           '任务派发',      'fHtOut',            '任务派发',         0,1,null,null,1,0,null,0,'fHtOut','cx.plug.fHtOut','plugin/xunjian/manfault/fHtOut/','fHtOut.js','fHtOut.html','fHtOutC.html','fHtOut',0,500,400,null,'{"_major":99,"_minor":13}');
/*任务审核意见*/        delete from plugin where name = 'fTaskCheckAdvice';  insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara)values ('11','fTaskCheckAdvice','fTaskCheckAdvice', '任务审核意见','fTaskCheckAdvice', '任务审核意见',     0,1,null,null,1,1,null,0,'fTaskCheckAdvice',    'cx.plug.fTaskCheckAdvice','plugin/xunjian/manfault/fTaskCheckAdvice/','fTaskCheckAdvice.js','fTaskCheckAdvice.html','fTaskCheckAdviceC.html',          null,      0,310,350, null,   null);
                        delete from plugin where name = 'FaultQue';           insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara)values  ('11','FaultQue','FaultQue', '故障查询',    'faultQue','故障查询',                           0,  1, null, null, 1,0,null, 0, 'FaultQue',  'cx.plug.FaultQue', 'plugin/xunjian/manfault/FaultQue/', 'FaultQue.js', 'FaultQue.html', 'FaultQueC.html', 'zoomin', 0, 500,350, null,'{"_major":1,"_minor":10}');
                        delete from plugin where name = 'FaultSta';           insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara)values  ('11', 'FaultSta', 'FaultSta', '故障统计', 'FaultSta', '故障统计',                           0,  1, null, null, 1,0,null, 0, 'FaultSta', 'cx.plug.FaultSta', 'plugin/xunjian/manfault/FaultSta/', 'FaultSta.js', 'FaultSta.html', 'FaultStaC.html', 'zoomin', 0, 500,350, null, '{"_major":1,"_minor":10}');
                        delete from plugin where name = 'TaskChe';            insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara)values  ('11', 'TaskChe', 'TaskChe', '任务审核', 'TaskChe', '任务审核',                               0,  1, null, null, 1,0,null, 0, 'TaskChe', 'cx.plug.TaskChe', 'plugin/xunjian/manfault/TaskChe/', 'TaskChe.js', 'TaskChe.html', 'TaskCheC.html',        'zoomin', 0, 600,350, null, '{"_major":7,"_minor":7}');
                        delete from plugin where name = 'TaskCheAdvice';     insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara)values  ('11', 'TaskCheAdvice', 'TaskCheAdvice', '任务审核意见', 'TaskCheAdvice', '任务审核意见',  0,  1, null, null, 1,0,null, 0, 'TaskCheAdvice', 'cx.plug.TaskCheAdvice', 'plugin/xunjian/manfault/TaskCheAdvice/', 'TaskCheAdvice.js', 'TaskCheAdvice.html', 'TaskCheAdviceC.html',  'zoomin',0, 310, 350, null, null);

/*巡检计划模块*/
/*新建片区*/            delete from plugin where name = 'NewArea';      insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara)values ('11', 'NewArea',    'NewArea',       '新建片区',     'NewArea',     '新建片区',     0,1,null,null,1,0,null,0, 'NewArea',         'cx.plug.NewArea',        'plugin/xunjian/xjplan/NewArea/',          'NewArea.js',      'NewArea.html',      'NewAreaC.html',     'drawcirc',0,150,150,null,  '{"alignH":1,"visible":false}');
/*片区管理*/            delete from plugin where name = 'AreaMan';      insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara)values ('11','AreaMan',     'AreaMan',       '片区管理',     'AreaMan',     '片区管理',     0,1,null,null,1,0,null,0, 'AreaMan',         'cx.plug.AreaMan',        'plugin/xunjian/xjplan/AreaMan/',          'AreaMan.js',      'AreaMan.html',   'AreaManC.html',             null,      0,500,450, null,'{"_major":3,"_minor":1,"_tabname":"patarea"}');
/*片区编辑*/            delete from plugin where name = 'NetwPntMov';   insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara)values ('11','NetwPntMov', 'NetwPntMov',    '片区编辑',     'NetwPntMov', '片区编辑',     0,1,null,null,1,0,null,0, 'NetwPntMov',      'cx.plug.NetwPntMov',     'plugin/xunjian/xjplan/NewArea/',          'NetwPntMov.js',  null,   null,                     null,      0,0,0, null,null);
/*模板制定*/            delete from plugin where name = 'Template';        insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara)values ('11','Template','Template',      '模板制定',       'Template',   '模板制定',    0,  1, null, null, 1, 0, null ,0, 'Template',  'cx.plug.Template',  'plugin/xunjian/xjplan/Template/',    'Template.js',   'Template.html',   'TemplateC.html', 'zoomin', 0, 550, 400, null, null);
/*新建片区设定*/        delete from plugin where name = 'NewAreaSet';      insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara)values  ('11','NewAreaSet','NewAreaSet',  '新建片区设置',   'NewAreaSet',  '新建片区设置',0, 1,null, null, 1, 0, null,0, 'NewAreaSet', 'cx.plug.NewAreaSet', 'plugin/xunjian/xjplan/NewAreaSet/',  'NewAreaSet.js', 'NewAreaSet.html', 'NewAreaSetC.html', null, 0, 300, 200, null, null);
/*新建任务*/            delete from plugin where name = 'MakeTask';        insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara)values  ('11','MakeTask','MakeTask',        '任务制定',      'MakeTask',    '任务制定',      0,  1, null, null, 1,0,null, 0, 'MakeTask',   'cx.plug.MakeTask',  'plugin/xunjian/xjplan/MakeTask/',    'MakeTask.js',  'MakeTask.html',      'MakeTaskC.html','zoomin',0,600,600,null,'{"_major":99,"_minor":13,"major_":7,"minor_":2}');
/*任务审核*/            delete from plugin where name = 'ShowTaskdet';    insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara)values  ('11','ShowTaskdet','ShowTaskdet',   '任务审核',      'MakeTask',   '任务审核',      0,  1, null, null, 1,0,null, 0, 'ShowTaskdet',   'cx.plug.ShowTaskdet',  'plugin/xunjian/xjplan/ShowTaskdet/',    'ShowTaskdet.js',  'ShowTaskdet.html',      'ShowTaskdetC.html','zoomin',0,550,400,null,'{"_major":7,"_minor":5}');
/*巡检任务审核意见*/    delete from plugin where name = 'TaskdetCheck';   insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara)values  ('11','TaskdetCheck','TaskdetCheck', '审核意见',    'TaskdetCheck','审核意见',      0,  1, null, null, 1,0,null, 0, 'TaskdetCheck',   'cx.plug.TaskdetCheck',  'plugin/xunjian/xjplan/ShowTaskdet/',  'TaskdetCheck.js',  'TaskdetCheck.html',      'TaskdetCheckC.html','zoomin',0,310,350,null, null);
/*片区报表*/            delete from plugin where name = 'DistrictReport';       insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara)values  ('11', 'DistrictReport', 'DistrictReport', '片区报表', 'DistrictReport', '片区报表',                          0,  1, null, null, 1,0,null, 0, 'DistrictReport', 'cx.plug.DistrictReport', 'plugin/xunjian/xjplan/DistrictReport/', 'DistrictReport.js','DistrictReport.html', 'DistrictReportC.html','zoomin',0,600, 350,null, '{"_major":3,"_minor":1}');
/*任务制定报表*/        delete from plugin where name = 'TaskSetReport';        insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara)values  ('11', 'TaskSetReport', 'TaskSetReport', '任务制定报表', 'TaskSetReport', '任务制定报表',                     0,  1, null, null, 1,0,null, 0, 'TaskSetReport', 'cx.plug.TaskSetReport', 'plugin/xunjian/xjplan/TaskSetReport/', 'TaskSetReport.js', 'TaskSetReport.html', 'TaskSetReportC.html','zoomin',0,600, 350,null, '{"_major":7,"_minor":4}');
/*任务实施报表*/        delete from plugin where name = 'TaskImplementReport'; insert into plugin(sys,name,namee,namec,titlee,titlec,autorun,closeable,autoobj,prereq,uitype,modal,container,runn,idui,plugin,dir,classurl,uiurle,uiurlc,icon,align,width,height,service,initpara)values  ('11', 'TaskImplementReport', 'TaskImplementReport', '任务实施报表', 'TaskImplementReport', '任务实施报表',0,  1, null, null, 1,0,null, 0, 'TaskImplementReport', 'cx.plug.TaskImplementReport', 'plugin/xunjian/xjplan/TaskImplementReport/', 'TaskImplementReport.js','TaskImplementReport.html', 'TaskImplementReportC.html','zoomin',0,600, 350,null, '{"_major":7,"_minor":5}');

