package com.autumnframework.login.dao.bomapper;

import com.autumnframework.login.model.po.Role;
import org.springframework.stereotype.Repository;

@Repository
public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_role
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_role
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_role
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_role
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_role
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_role
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    int updateByPrimaryKey(Role record);
}