package com.autumnframework.common.model.po;

import java.util.Date;

public class ArticleInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_articleinfo.id
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_articleinfo.user_id
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_articleinfo.user_name
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    private String user_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_articleinfo.title
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_articleinfo.abstracts
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    private String abstracts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_articleinfo.post_time
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    private Date post_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_articleinfo.modification_time
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    private Date modification_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_articleinfo.visit_times
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    private Integer visit_times;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_articleinfo.comment_times
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    private Integer comment_times;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_articleinfo.up_vote
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    private Integer up_vote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_articleinfo.down_vote
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    private Integer down_vote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_articleinfo.state
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_articleinfo.tags
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_articleinfo.type
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_articleinfo.visit_id
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    private String visit_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_articleinfo.privilege
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    private Integer privilege;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_articleinfo.id
     *
     * @return the value of af_articleinfo.id
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_articleinfo.id
     *
     * @param id the value for af_articleinfo.id
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_articleinfo.user_id
     *
     * @return the value of af_articleinfo.user_id
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_articleinfo.user_id
     *
     * @param user_id the value for af_articleinfo.user_id
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_articleinfo.user_name
     *
     * @return the value of af_articleinfo.user_name
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public String getUser_name() {
        return user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_articleinfo.user_name
     *
     * @param user_name the value for af_articleinfo.user_name
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public void setUser_name(String user_name) {
        this.user_name = user_name == null ? null : user_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_articleinfo.title
     *
     * @return the value of af_articleinfo.title
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_articleinfo.title
     *
     * @param title the value for af_articleinfo.title
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_articleinfo.abstracts
     *
     * @return the value of af_articleinfo.abstracts
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public String getAbstracts() {
        return abstracts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_articleinfo.abstracts
     *
     * @param abstracts the value for af_articleinfo.abstracts
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public void setAbstracts(String abstracts) {
        this.abstracts = abstracts == null ? null : abstracts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_articleinfo.post_time
     *
     * @return the value of af_articleinfo.post_time
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public Date getPost_time() {
        return post_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_articleinfo.post_time
     *
     * @param post_time the value for af_articleinfo.post_time
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public void setPost_time(Date post_time) {
        this.post_time = post_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_articleinfo.modification_time
     *
     * @return the value of af_articleinfo.modification_time
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public Date getModification_time() {
        return modification_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_articleinfo.modification_time
     *
     * @param modification_time the value for af_articleinfo.modification_time
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public void setModification_time(Date modification_time) {
        this.modification_time = modification_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_articleinfo.visit_times
     *
     * @return the value of af_articleinfo.visit_times
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public Integer getVisit_times() {
        return visit_times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_articleinfo.visit_times
     *
     * @param visit_times the value for af_articleinfo.visit_times
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public void setVisit_times(Integer visit_times) {
        this.visit_times = visit_times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_articleinfo.comment_times
     *
     * @return the value of af_articleinfo.comment_times
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public Integer getComment_times() {
        return comment_times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_articleinfo.comment_times
     *
     * @param comment_times the value for af_articleinfo.comment_times
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public void setComment_times(Integer comment_times) {
        this.comment_times = comment_times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_articleinfo.up_vote
     *
     * @return the value of af_articleinfo.up_vote
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public Integer getUp_vote() {
        return up_vote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_articleinfo.up_vote
     *
     * @param up_vote the value for af_articleinfo.up_vote
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public void setUp_vote(Integer up_vote) {
        this.up_vote = up_vote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_articleinfo.down_vote
     *
     * @return the value of af_articleinfo.down_vote
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public Integer getDown_vote() {
        return down_vote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_articleinfo.down_vote
     *
     * @param down_vote the value for af_articleinfo.down_vote
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public void setDown_vote(Integer down_vote) {
        this.down_vote = down_vote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_articleinfo.state
     *
     * @return the value of af_articleinfo.state
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_articleinfo.state
     *
     * @param state the value for af_articleinfo.state
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_articleinfo.tags
     *
     * @return the value of af_articleinfo.tags
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_articleinfo.tags
     *
     * @param tags the value for af_articleinfo.tags
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_articleinfo.type
     *
     * @return the value of af_articleinfo.type
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_articleinfo.type
     *
     * @param type the value for af_articleinfo.type
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_articleinfo.visit_id
     *
     * @return the value of af_articleinfo.visit_id
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public String getVisit_id() {
        return visit_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_articleinfo.visit_id
     *
     * @param visit_id the value for af_articleinfo.visit_id
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public void setVisit_id(String visit_id) {
        this.visit_id = visit_id == null ? null : visit_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_articleinfo.privilege
     *
     * @return the value of af_articleinfo.privilege
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public Integer getPrivilege() {
        return privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_articleinfo.privilege
     *
     * @param privilege the value for af_articleinfo.privilege
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    public void setPrivilege(Integer privilege) {
        this.privilege = privilege;
    }
}