package com.autumnframework.common.dao.bomapper;

import com.autumnframework.common.model.po.ArticleInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ArticleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_articleinfo
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_articleinfo
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    int insert(ArticleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_articleinfo
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    int insertSelective(ArticleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_articleinfo
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    ArticleInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_articleinfo
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    int updateByPrimaryKeySelective(ArticleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_articleinfo
     *
     * @mbg.generated Fri Apr 20 18:07:11 CST 2018
     */
    int updateByPrimaryKey(ArticleInfo record);

    /**
     *
     * @return
     */
    List<ArticleInfo> getArticleList();

    /**
     *
     * @param visitTimes
     * @param visitId
     * @return
     */
    int updateVisitTimes(@Param("visitTimes") Integer visitTimes, @Param("visitId") String visitId);

    /**
     *
     * @param visitId
     * @return
     */
    List<ArticleInfo> getArticleByVisitId(@Param("visitId") String visitId);
}