package com.autumnframework.login.dao.bomapper;

import com.autumnframework.login.model.po.User;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_user
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_user
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_user
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_user
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_user
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_user
     *
     * @mbg.generated Wed Oct 25 15:36:28 CST 2017
     */
    int updateByPrimaryKey(User record);
    /**
     * 根据登陆用户名和状态查询用户信息
     * @param userLoginName
     * @param userStatus
     * @return
     */
    User selectUserByloginNameAndStatus(@Param("userLoginName") String userLoginName, @Param("userStatus") Long userStatus);


}